# NOTE: Generated By HttpRunner v3.1.4
# FROM: testcases\hogs.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseHogs(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/")
            .get("https://mubu.com/")
            .with_headers(
                **{
                    "cache-control": "max-age=0",
                    "upgrade-insecure-requests": "1",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "none",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "944e79f5-b0a0-4ac8-8fd3-3d45b810d3b3",
                    "use-redesign": "1",
                    "csrf_token": "800ffb3f-2b24-4089-b71d-419cc16c4fae",
                    "language": "en-US",
                    "country": "US",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2F",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1612253972,1612344469,1612431127",
                    "SESSION": "8105c8cb-19f6-4f72-bcdf-64efa80fd6f5",
                    "reg_prepareId": "1776c69a96c-1776c69a914-4d76-a30b-29d265d2c4cb",
                    "reg_focusId": "44b4507d-ceb0-4d76-a30b-1776c69bb78",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1612431622",
                    "SLARDAR_WEB_ID": "a2e71275-5ec2-4822-a475-80a3a87b1c2a",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/login")
            .get("https://mubu.com/login")
            .with_headers(
                **{
                    "upgrade-insecure-requests": "1",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "944e79f5-b0a0-4ac8-8fd3-3d45b810d3b3",
                    "use-redesign": "1",
                    "csrf_token": "800ffb3f-2b24-4089-b71d-419cc16c4fae",
                    "language": "en-US",
                    "country": "US",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2F",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1612253972,1612344469,1612431127",
                    "SESSION": "8105c8cb-19f6-4f72-bcdf-64efa80fd6f5",
                    "reg_prepareId": "1776c69a96c-1776c69a914-4d76-a30b-29d265d2c4cb",
                    "reg_focusId": "44b4507d-ceb0-4d76-a30b-1776c69bb78",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1612431630",
                    "SLARDAR_WEB_ID": "972f06e5-ab46-4bad-8667-96b4e7f83a05",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/login/password")
            .get("https://mubu.com/login/password")
            .with_headers(
                **{
                    "upgrade-insecure-requests": "1",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "referer": "https://mubu.com/login",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "944e79f5-b0a0-4ac8-8fd3-3d45b810d3b3",
                    "use-redesign": "1",
                    "csrf_token": "800ffb3f-2b24-4089-b71d-419cc16c4fae",
                    "language": "en-US",
                    "country": "US",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2F",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1612253972,1612344469,1612431127",
                    "SESSION": "8105c8cb-19f6-4f72-bcdf-64efa80fd6f5",
                    "reg_prepareId": "1776c6a268f-1776c6a2668-4449-b840-e77dab22130b",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1612431632",
                    "SLARDAR_WEB_ID": "b9e0a38a-77fa-4c63-b854-4e9e949b692c",
                    "reg_focusId": "e9ef39b1-b965-4449-b840-1776c6a29e5",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/api/login/submit")
            .post("https://mubu.com/api/login/submit")
            .with_headers(
                **{
                    "content-length": "47",
                    "accept": "application/json, text/javascript, */*; q=0.01",
                    "x-requested-with": "XMLHttpRequest",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36",
                    "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/login/password",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "944e79f5-b0a0-4ac8-8fd3-3d45b810d3b3",
                    "use-redesign": "1",
                    "csrf_token": "800ffb3f-2b24-4089-b71d-419cc16c4fae",
                    "language": "en-US",
                    "country": "US",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2F",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1612253972,1612344469,1612431127",
                    "SESSION": "8105c8cb-19f6-4f72-bcdf-64efa80fd6f5",
                    "reg_prepareId": "1776c6a268f-1776c6a2668-4449-b840-e77dab22130b",
                    "reg_focusId": "e9ef39b1-b965-4449-b840-1776c6a29e5",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1612431633",
                    "SLARDAR_WEB_ID": "d6e2c935-bfcc-4021-a0c8-0bb5ca474d27",
                }
            )
            .with_data(
                {"phone": "18633046286", "password": "123456", "remember": "true"}
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal(
                'headers."Content-Type"', "application/json;charset=UTF-8;charset=UTF-8"
            )
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
        ),
        Step(
            RunRequest("/app")
            .get("https://mubu.com/app")
            .with_headers(
                **{
                    "upgrade-insecure-requests": "1",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "referer": "https://mubu.com/login/password",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "944e79f5-b0a0-4ac8-8fd3-3d45b810d3b3",
                    "use-redesign": "1",
                    "csrf_token": "800ffb3f-2b24-4089-b71d-419cc16c4fae",
                    "language": "en-US",
                    "country": "US",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2F",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1612253972,1612344469,1612431127",
                    "SESSION": "8105c8cb-19f6-4f72-bcdf-64efa80fd6f5",
                    "reg_prepareId": "1776c6a268f-1776c6a2668-4449-b840-e77dab22130b",
                    "reg_focusId": "e9ef39b1-b965-4449-b840-1776c6a29e5",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1612431633",
                    "SLARDAR_WEB_ID": "d6e2c935-bfcc-4021-a0c8-0bb5ca474d27",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTA4OTU1MzYiLCJleHAiOjE2MTUwMjM2NDEsImlhdCI6MTYxMjQzMTY0MX0.KnPbUCPymXPAisYoxKTy7A2YsySJbMm2w6HowJEeUZjFz1EBm5WIzkGk2K1wEM4yZJ5fpDJU4XlcsyPb-sYieg",
                    "user_persistence": "02679bc6-142e-4b7b-8a7b-695200733f33",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/message/get_message_unread")
            .post("https://api2.mubu.com/v3/api/message/get_message_unread")
            .with_headers(
                **{
                    "content-length": "10",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTA4OTU1MzYiLCJleHAiOjE2MTUwMjM2NDEsImlhdCI6MTYxMjQzMTY0MX0.KnPbUCPymXPAisYoxKTy7A2YsySJbMm2w6HowJEeUZjFz1EBm5WIzkGk2K1wEM4yZJ5fpDJU4XlcsyPb-sYieg",
                    "Content-Type": "application/json;charset=UTF-8;charset=UTF-8",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36",
                    "data-unique-id": "944e79f5-b0a0-4ac8-8fd3-3d45b810d3b3",
                    "x-request-id": "75da4d3f-2b98-47a8-8bf1-8fbe9042fe4d",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"page": 1})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal(
                'headers."Content-Type"', "application/json;charset=UTF-8;charset=UTF-8"
            )
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/")
            .get("https://api2.mubu.com/v3/")
            .with_headers(
                **{
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36",
                    "accept": "image/avif,image/webp,image/apng,image/*,*/*;q=0.8",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "no-cors",
                    "sec-fetch-dest": "image",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "use-redesign": "1",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1612253972,1612344469,1612431127",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1612431633",
                    "SLARDAR_WEB_ID": "bf800fac-196c-4f9f-91cc-d22e2438e07d",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal(
                'headers."Content-Type"', "application/json;charset=UTF-8;charset=UTF-8"
            )
            .assert_equal("body.code", 17)
            .assert_equal("body.msg", "illegal request")
        ),
        Step(
            RunRequest("/v3/api/list/star_relation/get")
            .get("https://api2.mubu.com/v3/api/list/star_relation/get")
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTA4OTU1MzYiLCJleHAiOjE2MTUwMjM2NDEsImlhdCI6MTYxMjQzMTY0MX0.KnPbUCPymXPAisYoxKTy7A2YsySJbMm2w6HowJEeUZjFz1EBm5WIzkGk2K1wEM4yZJ5fpDJU4XlcsyPb-sYieg",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36",
                    "data-unique-id": "944e79f5-b0a0-4ac8-8fd3-3d45b810d3b3",
                    "x-request-id": "0cc6f425-2a6e-4fcf-9eee-4afde5140cf8",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal(
                'headers."Content-Type"', "application/json;charset=UTF-8;charset=UTF-8"
            )
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/get_all_documents_page")
            .post("https://api2.mubu.com/v3/api/list/get_all_documents_page")
            .with_headers(
                **{
                    "content-length": "12",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTA4OTU1MzYiLCJleHAiOjE2MTUwMjM2NDEsImlhdCI6MTYxMjQzMTY0MX0.KnPbUCPymXPAisYoxKTy7A2YsySJbMm2w6HowJEeUZjFz1EBm5WIzkGk2K1wEM4yZJ5fpDJU4XlcsyPb-sYieg",
                    "Content-Type": "application/json;charset=UTF-8;charset=UTF-8",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36",
                    "data-unique-id": "944e79f5-b0a0-4ac8-8fd3-3d45b810d3b3",
                    "x-request-id": "1086418d-8301-43ab-a04f-ea6514602e63",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"start": ""})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal(
                'headers."Content-Type"', "application/json;charset=UTF-8;charset=UTF-8"
            )
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/user/profile")
            .post("https://api2.mubu.com/v3/api/user/profile")
            .with_headers(
                **{
                    "content-length": "0",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTA4OTU1MzYiLCJleHAiOjE2MTUwMjM2NDEsImlhdCI6MTYxMjQzMTY0MX0.KnPbUCPymXPAisYoxKTy7A2YsySJbMm2w6HowJEeUZjFz1EBm5WIzkGk2K1wEM4yZJ5fpDJU4XlcsyPb-sYieg",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36",
                    "data-unique-id": "944e79f5-b0a0-4ac8-8fd3-3d45b810d3b3",
                    "x-request-id": "2408abe0-8cf3-48bb-a70a-3dcb33521cf1",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal(
                'headers."Content-Type"', "application/json;charset=UTF-8;charset=UTF-8"
            )
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/advertisement/get")
            .post("https://api2.mubu.com/v3/api/advertisement/get")
            .with_headers(
                **{
                    "content-length": "10",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTA4OTU1MzYiLCJleHAiOjE2MTUwMjM2NDEsImlhdCI6MTYxMjQzMTY0MX0.KnPbUCPymXPAisYoxKTy7A2YsySJbMm2w6HowJEeUZjFz1EBm5WIzkGk2K1wEM4yZJ5fpDJU4XlcsyPb-sYieg",
                    "Content-Type": "application/json;charset=UTF-8;charset=UTF-8",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36",
                    "data-unique-id": "944e79f5-b0a0-4ac8-8fd3-3d45b810d3b3",
                    "x-request-id": "141fb45e-7dfb-4bac-88dd-167055977ab5",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"type": 1})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal(
                'headers."Content-Type"', "application/json;charset=UTF-8;charset=UTF-8"
            )
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/item_count")
            .post("https://api2.mubu.com/v3/api/list/item_count")
            .with_headers(
                **{
                    "content-length": "30",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTA4OTU1MzYiLCJleHAiOjE2MTUwMjM2NDEsImlhdCI6MTYxMjQzMTY0MX0.KnPbUCPymXPAisYoxKTy7A2YsySJbMm2w6HowJEeUZjFz1EBm5WIzkGk2K1wEM4yZJ5fpDJU4XlcsyPb-sYieg",
                    "Content-Type": "application/json;charset=UTF-8;charset=UTF-8",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36",
                    "data-unique-id": "944e79f5-b0a0-4ac8-8fd3-3d45b810d3b3",
                    "x-request-id": "9511165b-cb6f-45a6-ac79-aa422a82cf78",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"folderId": 0, "source": "home"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal(
                'headers."Content-Type"', "application/json;charset=UTF-8;charset=UTF-8"
            )
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/user/get_user_params")
            .post("https://api2.mubu.com/v3/api/user/get_user_params")
            .with_headers(
                **{
                    "content-length": "0",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTA4OTU1MzYiLCJleHAiOjE2MTUwMjM2NDEsImlhdCI6MTYxMjQzMTY0MX0.KnPbUCPymXPAisYoxKTy7A2YsySJbMm2w6HowJEeUZjFz1EBm5WIzkGk2K1wEM4yZJ5fpDJU4XlcsyPb-sYieg",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36",
                    "data-unique-id": "944e79f5-b0a0-4ac8-8fd3-3d45b810d3b3",
                    "x-request-id": "cf692b80-ba60-449e-9c23-7ddd3f6760a5",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal(
                'headers."Content-Type"', "application/json;charset=UTF-8;charset=UTF-8"
            )
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/create_folder")
            .options("https://api2.mubu.com/v3/api/list/create_folder")
            .with_headers(
                **{
                    "accept": "*/*",
                    "access-control-request-method": "POST",
                    "access-control-request-headers": "content-type,data-unique-id,jwt-token,version,x-request-id",
                    "origin": "https://mubu.com",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/list/create_folder")
            .post("https://api2.mubu.com/v3/api/list/create_folder")
            .with_headers(
                **{
                    "content-length": "30",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTA4OTU1MzYiLCJleHAiOjE2MTUwMjM2NDEsImlhdCI6MTYxMjQzMTY0MX0.KnPbUCPymXPAisYoxKTy7A2YsySJbMm2w6HowJEeUZjFz1EBm5WIzkGk2K1wEM4yZJ5fpDJU4XlcsyPb-sYieg",
                    "Content-Type": "application/json;charset=UTF-8;charset=UTF-8",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36",
                    "data-unique-id": "944e79f5-b0a0-4ac8-8fd3-3d45b810d3b3",
                    "x-request-id": "e4b2ef65-9e25-4ead-86d4-b17058916a86",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"name": "test", "folderId": "0"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal(
                'headers."Content-Type"', "application/json;charset=UTF-8;charset=UTF-8"
            )
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/create_doc")
            .options("https://api2.mubu.com/v3/api/list/create_doc")
            .with_headers(
                **{
                    "accept": "*/*",
                    "access-control-request-method": "POST",
                    "access-control-request-headers": "content-type,data-unique-id,jwt-token,version,x-request-id",
                    "origin": "https://mubu.com",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/list/create_doc")
            .post("https://api2.mubu.com/v3/api/list/create_doc")
            .with_headers(
                **{
                    "content-length": "34",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTA4OTU1MzYiLCJleHAiOjE2MTUwMjM2NDEsImlhdCI6MTYxMjQzMTY0MX0.KnPbUCPymXPAisYoxKTy7A2YsySJbMm2w6HowJEeUZjFz1EBm5WIzkGk2K1wEM4yZJ5fpDJU4XlcsyPb-sYieg",
                    "Content-Type": "application/json;charset=UTF-8;charset=UTF-8",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36",
                    "data-unique-id": "944e79f5-b0a0-4ac8-8fd3-3d45b810d3b3",
                    "x-request-id": "edcebd19-b9c7-4cf1-a84e-0061eb9ca3f6",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"folderId": "17-Z9Uagxg", "type": 0})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal(
                'headers."Content-Type"', "application/json;charset=UTF-8;charset=UTF-8"
            )
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/item_count")
            .post("https://api2.mubu.com/v3/api/list/item_count")
            .with_headers(
                **{
                    "content-length": "30",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTA4OTU1MzYiLCJleHAiOjE2MTUwMjM2NDEsImlhdCI6MTYxMjQzMTY0MX0.KnPbUCPymXPAisYoxKTy7A2YsySJbMm2w6HowJEeUZjFz1EBm5WIzkGk2K1wEM4yZJ5fpDJU4XlcsyPb-sYieg",
                    "Content-Type": "application/json;charset=UTF-8;charset=UTF-8",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36",
                    "data-unique-id": "944e79f5-b0a0-4ac8-8fd3-3d45b810d3b3",
                    "x-request-id": "ba11ad07-e56a-47a0-9078-2001cc2be30f",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"folderId": 0, "source": "home"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal(
                'headers."Content-Type"', "application/json;charset=UTF-8;charset=UTF-8"
            )
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/user/current_level")
            .options("https://api2.mubu.com/v3/api/user/current_level")
            .with_headers(
                **{
                    "accept": "*/*",
                    "access-control-request-method": "POST",
                    "access-control-request-headers": "content-type,data-unique-id,jwt-token,version,x-request-id",
                    "origin": "https://mubu.com",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/document/edit/get")
            .options("https://api2.mubu.com/v3/api/document/edit/get")
            .with_headers(
                **{
                    "accept": "*/*",
                    "access-control-request-method": "POST",
                    "access-control-request-headers": "content-type,data-unique-id,jwt-token,version,x-request-id",
                    "origin": "https://mubu.com",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/user/current_level")
            .post("https://api2.mubu.com/v3/api/user/current_level")
            .with_headers(
                **{
                    "content-length": "28",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTA4OTU1MzYiLCJleHAiOjE2MTUwMjM2NDEsImlhdCI6MTYxMjQzMTY0MX0.KnPbUCPymXPAisYoxKTy7A2YsySJbMm2w6HowJEeUZjFz1EBm5WIzkGk2K1wEM4yZJ5fpDJU4XlcsyPb-sYieg",
                    "Content-Type": "application/json;charset=UTF-8;charset=UTF-8",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36",
                    "data-unique-id": "944e79f5-b0a0-4ac8-8fd3-3d45b810d3b3",
                    "x-request-id": "001221fc-b587-4676-864d-0b98f35a08e4",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"document_id": "Js82Laivxg"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal(
                'headers."Content-Type"', "application/json;charset=UTF-8;charset=UTF-8"
            )
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/document/edit/get")
            .post("https://api2.mubu.com/v3/api/document/edit/get")
            .with_headers(
                **{
                    "content-length": "36",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTA4OTU1MzYiLCJleHAiOjE2MTUwMjM2NDEsImlhdCI6MTYxMjQzMTY0MX0.KnPbUCPymXPAisYoxKTy7A2YsySJbMm2w6HowJEeUZjFz1EBm5WIzkGk2K1wEM4yZJ5fpDJU4XlcsyPb-sYieg",
                    "Content-Type": "application/json;charset=UTF-8;charset=UTF-8",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36",
                    "data-unique-id": "944e79f5-b0a0-4ac8-8fd3-3d45b810d3b3",
                    "x-request-id": "1fef26bc-e243-4544-84a1-e8658297ad50",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"docId": "Js82Laivxg", "password": ""})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal(
                'headers."Content-Type"', "application/json;charset=UTF-8;charset=UTF-8"
            )
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/register")
            .options("https://api2.mubu.com/v3/api/colla/register")
            .with_headers(
                **{
                    "accept": "*/*",
                    "access-control-request-method": "GET",
                    "access-control-request-headers": "data-unique-id,jwt-token,x-request-id",
                    "origin": "https://mubu.com",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/refer/doc/list")
            .options("https://api2.mubu.com/v3/api/refer/doc/list")
            .with_headers(
                **{
                    "accept": "*/*",
                    "access-control-request-method": "POST",
                    "access-control-request-headers": "content-type,data-unique-id,jwt-token,x-request-id",
                    "origin": "https://mubu.com",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/colla/register")
            .get("https://api2.mubu.com/v3/api/colla/register")
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTA4OTU1MzYiLCJleHAiOjE2MTUwMjM2NDEsImlhdCI6MTYxMjQzMTY0MX0.KnPbUCPymXPAisYoxKTy7A2YsySJbMm2w6HowJEeUZjFz1EBm5WIzkGk2K1wEM4yZJ5fpDJU4XlcsyPb-sYieg",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36",
                    "data-unique-id": "944e79f5-b0a0-4ac8-8fd3-3d45b810d3b3",
                    "x-request-id": "61f82f14-2dcd-4090-8549-be9d2c893918",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal(
                'headers."Content-Type"', "application/json;charset=UTF-8;charset=UTF-8"
            )
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/refer/doc/list")
            .post("https://api2.mubu.com/v3/api/refer/doc/list")
            .with_headers(
                **{
                    "content-length": "28",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTA4OTU1MzYiLCJleHAiOjE2MTUwMjM2NDEsImlhdCI6MTYxMjQzMTY0MX0.KnPbUCPymXPAisYoxKTy7A2YsySJbMm2w6HowJEeUZjFz1EBm5WIzkGk2K1wEM4yZJ5fpDJU4XlcsyPb-sYieg",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36",
                    "data-unique-id": "944e79f5-b0a0-4ac8-8fd3-3d45b810d3b3",
                    "x-request-id": "4220de49-5143-46c5-b265-1af69c63c7b0",
                    "Content-Type": "application/json;charset=UTF-8;charset=UTF-8",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"targetDocId": "Js82Laivxg"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal(
                'headers."Content-Type"', "application/json;charset=UTF-8;charset=UTF-8"
            )
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/members")
            .options("https://api2.mubu.com/v3/api/colla/members")
            .with_params(**{"memberId": "8329105351842932", "documentId": "Js82Laivxg"})
            .with_headers(
                **{
                    "accept": "*/*",
                    "access-control-request-method": "GET",
                    "access-control-request-headers": "data-unique-id,jwt-token,request-id,x-request-id",
                    "origin": "https://mubu.com",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/colla/members")
            .get("https://api2.mubu.com/v3/api/colla/members")
            .with_params(**{"memberId": "8329105351842932", "documentId": "Js82Laivxg"})
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTA4OTU1MzYiLCJleHAiOjE2MTUwMjM2NDEsImlhdCI6MTYxMjQzMTY0MX0.KnPbUCPymXPAisYoxKTy7A2YsySJbMm2w6HowJEeUZjFz1EBm5WIzkGk2K1wEM4yZJ5fpDJU4XlcsyPb-sYieg",
                    "request-id": "members:8329105351842932:1612431656126",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36",
                    "data-unique-id": "944e79f5-b0a0-4ac8-8fd3-3d45b810d3b3",
                    "x-request-id": "5a07ddd6-053d-4854-929f-ceb180f4f345",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal(
                'headers."Content-Type"', "application/json;charset=UTF-8;charset=UTF-8"
            )
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .options("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "accept": "*/*",
                    "access-control-request-method": "POST",
                    "access-control-request-headers": "content-type,data-unique-id,jwt-token,member-id,request-id,version,x-request-id",
                    "origin": "https://mubu.com",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "358",
                    "member-id": "8329105351842932",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36",
                    "data-unique-id": "944e79f5-b0a0-4ac8-8fd3-3d45b810d3b3",
                    "Content-Type": "application/json;charset=UTF-8;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTA4OTU1MzYiLCJleHAiOjE2MTUwMjM2NDEsImlhdCI6MTYxMjQzMTY0MX0.KnPbUCPymXPAisYoxKTy7A2YsySJbMm2w6HowJEeUZjFz1EBm5WIzkGk2K1wEM4yZJ5fpDJU4XlcsyPb-sYieg",
                    "request-id": "MESSAGE:10895536:8329105351842932:3",
                    "x-request-id": "da75504a-3731-4882-8512-49eaf79c25aa",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 3,
                    "requestId": "MESSAGE:10895536:8329105351842932:3",
                    "token": "Js82Laivxg",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "Js82Laivxg",
                            "version": 0,
                            "content": [
                                {"name": "nameChanged", "title": "test", "original": ""}
                            ],
                        }
                    },
                    "context": {
                        "os": "Windows",
                        "osVersion": "NT 10.0",
                        "appVersion": "2.0.0.825",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal(
                'headers."Content-Type"', "application/json;charset=UTF-8;charset=UTF-8"
            )
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "368",
                    "member-id": "8329105351842932",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36",
                    "data-unique-id": "944e79f5-b0a0-4ac8-8fd3-3d45b810d3b3",
                    "Content-Type": "application/json;charset=UTF-8;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTA4OTU1MzYiLCJleHAiOjE2MTUwMjM2NDEsImlhdCI6MTYxMjQzMTY0MX0.KnPbUCPymXPAisYoxKTy7A2YsySJbMm2w6HowJEeUZjFz1EBm5WIzkGk2K1wEM4yZJ5fpDJU4XlcsyPb-sYieg",
                    "request-id": "MESSAGE:10895536:8329105351842932:5",
                    "x-request-id": "fa2d9eb4-1245-479f-89e9-df87d2012b3a",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 5,
                    "requestId": "MESSAGE:10895536:8329105351842932:5",
                    "token": "Js82Laivxg",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "Js82Laivxg",
                            "version": 1,
                            "content": [
                                {
                                    "name": "nameChanged",
                                    "title": "test文档",
                                    "original": "test",
                                }
                            ],
                        }
                    },
                    "context": {
                        "os": "Windows",
                        "osVersion": "NT 10.0",
                        "appVersion": "2.0.0.825",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal(
                'headers."Content-Type"', "application/json;charset=UTF-8;charset=UTF-8"
            )
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "459",
                    "member-id": "8329105351842932",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36",
                    "data-unique-id": "944e79f5-b0a0-4ac8-8fd3-3d45b810d3b3",
                    "Content-Type": "application/json;charset=UTF-8;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTA4OTU1MzYiLCJleHAiOjE2MTUwMjM2NDEsImlhdCI6MTYxMjQzMTY0MX0.KnPbUCPymXPAisYoxKTy7A2YsySJbMm2w6HowJEeUZjFz1EBm5WIzkGk2K1wEM4yZJ5fpDJU4XlcsyPb-sYieg",
                    "request-id": "MESSAGE:10895536:8329105351842932:7",
                    "x-request-id": "bb7a9cf7-c9eb-46c5-9383-1d99e7005e34",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 7,
                    "requestId": "MESSAGE:10895536:8329105351842932:7",
                    "token": "Js82Laivxg",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "Js82Laivxg",
                            "version": 2,
                            "content": [
                                {
                                    "name": "create",
                                    "created": [
                                        {
                                            "index": 0,
                                            "parentId": None,
                                            "node": {
                                                "id": "j2tpGlZbzw",
                                                "text": "",
                                                "modified": 1612431659670,
                                                "children": [],
                                            },
                                            "path": ["nodes", 0],
                                        }
                                    ],
                                }
                            ],
                        }
                    },
                    "context": {
                        "os": "Windows",
                        "osVersion": "NT 10.0",
                        "appVersion": "2.0.0.825",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal(
                'headers."Content-Type"', "application/json;charset=UTF-8;charset=UTF-8"
            )
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/refer/search_refers")
            .options("https://api2.mubu.com/v3/api/refer/search_refers")
            .with_headers(
                **{
                    "accept": "*/*",
                    "access-control-request-method": "POST",
                    "access-control-request-headers": "content-type,data-unique-id,jwt-token,x-request-id",
                    "origin": "https://mubu.com",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/refer/search_refers")
            .post("https://api2.mubu.com/v3/api/refer/search_refers")
            .with_headers(
                **{
                    "content-length": "57",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTA4OTU1MzYiLCJleHAiOjE2MTUwMjM2NDEsImlhdCI6MTYxMjQzMTY0MX0.KnPbUCPymXPAisYoxKTy7A2YsySJbMm2w6HowJEeUZjFz1EBm5WIzkGk2K1wEM4yZJ5fpDJU4XlcsyPb-sYieg",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36",
                    "data-unique-id": "944e79f5-b0a0-4ac8-8fd3-3d45b810d3b3",
                    "x-request-id": "1bff3584-9e37-4177-b85c-5384c224752b",
                    "Content-Type": "application/json;charset=UTF-8;charset=UTF-8",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"docId": "Js82Laivxg", "keywords": "test文档", "option": 1})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal(
                'headers."Content-Type"', "application/json;charset=UTF-8;charset=UTF-8"
            )
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "502",
                    "member-id": "8329105351842932",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36",
                    "data-unique-id": "944e79f5-b0a0-4ac8-8fd3-3d45b810d3b3",
                    "Content-Type": "application/json;charset=UTF-8;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTA4OTU1MzYiLCJleHAiOjE2MTUwMjM2NDEsImlhdCI6MTYxMjQzMTY0MX0.KnPbUCPymXPAisYoxKTy7A2YsySJbMm2w6HowJEeUZjFz1EBm5WIzkGk2K1wEM4yZJ5fpDJU4XlcsyPb-sYieg",
                    "request-id": "MESSAGE:10895536:8329105351842932:9",
                    "x-request-id": "7f2f1150-a7e4-4eef-9b63-e6dc29967ca8",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 9,
                    "requestId": "MESSAGE:10895536:8329105351842932:9",
                    "token": "Js82Laivxg",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "Js82Laivxg",
                            "version": 3,
                            "content": [
                                {
                                    "name": "update",
                                    "updated": [
                                        {
                                            "updated": {
                                                "id": "j2tpGlZbzw",
                                                "text": "<span>1</span>",
                                                "modified": 1612431660928,
                                            },
                                            "original": {
                                                "id": "j2tpGlZbzw",
                                                "text": "",
                                                "modified": 1612431659670,
                                            },
                                            "path": ["nodes", 0],
                                        }
                                    ],
                                }
                            ],
                        }
                    },
                    "context": {
                        "os": "Windows",
                        "osVersion": "NT 10.0",
                        "appVersion": "2.0.0.825",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal(
                'headers."Content-Type"', "application/json;charset=UTF-8;charset=UTF-8"
            )
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "674",
                    "member-id": "8329105351842932",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36",
                    "data-unique-id": "944e79f5-b0a0-4ac8-8fd3-3d45b810d3b3",
                    "Content-Type": "application/json;charset=UTF-8;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTA4OTU1MzYiLCJleHAiOjE2MTUwMjM2NDEsImlhdCI6MTYxMjQzMTY0MX0.KnPbUCPymXPAisYoxKTy7A2YsySJbMm2w6HowJEeUZjFz1EBm5WIzkGk2K1wEM4yZJ5fpDJU4XlcsyPb-sYieg",
                    "request-id": "MESSAGE:10895536:8329105351842932:11",
                    "x-request-id": "0b299953-86ff-4980-a607-02ee20af5bd0",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 11,
                    "requestId": "MESSAGE:10895536:8329105351842932:11",
                    "token": "Js82Laivxg",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "Js82Laivxg",
                            "version": 4,
                            "content": [
                                {
                                    "name": "update",
                                    "updated": [
                                        {
                                            "updated": {
                                                "id": "j2tpGlZbzw",
                                                "text": "<span>1行</span>",
                                                "modified": 1612431663121,
                                            },
                                            "original": {
                                                "id": "j2tpGlZbzw",
                                                "text": "<span>1</span>",
                                                "modified": 1612431660928,
                                            },
                                            "path": ["nodes", 0],
                                        }
                                    ],
                                },
                                {
                                    "name": "create",
                                    "created": [
                                        {
                                            "index": 1,
                                            "parentId": None,
                                            "node": {
                                                "id": "LHs9wIriCq",
                                                "text": "",
                                                "modified": 1612431663536,
                                                "children": [],
                                            },
                                            "path": ["nodes", 1],
                                        }
                                    ],
                                },
                            ],
                        }
                    },
                    "context": {
                        "os": "Windows",
                        "osVersion": "NT 10.0",
                        "appVersion": "2.0.0.825",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal(
                'headers."Content-Type"', "application/json;charset=UTF-8;charset=UTF-8"
            )
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "504",
                    "member-id": "8329105351842932",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36",
                    "data-unique-id": "944e79f5-b0a0-4ac8-8fd3-3d45b810d3b3",
                    "Content-Type": "application/json;charset=UTF-8;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTA4OTU1MzYiLCJleHAiOjE2MTUwMjM2NDEsImlhdCI6MTYxMjQzMTY0MX0.KnPbUCPymXPAisYoxKTy7A2YsySJbMm2w6HowJEeUZjFz1EBm5WIzkGk2K1wEM4yZJ5fpDJU4XlcsyPb-sYieg",
                    "request-id": "MESSAGE:10895536:8329105351842932:13",
                    "x-request-id": "059c1579-9aef-4335-b564-8dddd8c69a28",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 13,
                    "requestId": "MESSAGE:10895536:8329105351842932:13",
                    "token": "Js82Laivxg",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "Js82Laivxg",
                            "version": 5,
                            "content": [
                                {
                                    "name": "update",
                                    "updated": [
                                        {
                                            "updated": {
                                                "id": "LHs9wIriCq",
                                                "text": "<span>2</span>",
                                                "modified": 1612431664366,
                                            },
                                            "original": {
                                                "id": "LHs9wIriCq",
                                                "text": "",
                                                "modified": 1612431663536,
                                            },
                                            "path": ["nodes", 1],
                                        }
                                    ],
                                }
                            ],
                        }
                    },
                    "context": {
                        "os": "Windows",
                        "osVersion": "NT 10.0",
                        "appVersion": "2.0.0.825",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal(
                'headers."Content-Type"', "application/json;charset=UTF-8;charset=UTF-8"
            )
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "521",
                    "member-id": "8329105351842932",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36",
                    "data-unique-id": "944e79f5-b0a0-4ac8-8fd3-3d45b810d3b3",
                    "Content-Type": "application/json;charset=UTF-8;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTA4OTU1MzYiLCJleHAiOjE2MTUwMjM2NDEsImlhdCI6MTYxMjQzMTY0MX0.KnPbUCPymXPAisYoxKTy7A2YsySJbMm2w6HowJEeUZjFz1EBm5WIzkGk2K1wEM4yZJ5fpDJU4XlcsyPb-sYieg",
                    "request-id": "MESSAGE:10895536:8329105351842932:15",
                    "x-request-id": "69d62528-d221-4d78-afd5-96f9ec3a6bd6",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 15,
                    "requestId": "MESSAGE:10895536:8329105351842932:15",
                    "token": "Js82Laivxg",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "Js82Laivxg",
                            "version": 6,
                            "content": [
                                {
                                    "name": "update",
                                    "updated": [
                                        {
                                            "updated": {
                                                "id": "LHs9wIriCq",
                                                "text": "<span>2行</span>",
                                                "modified": 1612431664992,
                                            },
                                            "original": {
                                                "id": "LHs9wIriCq",
                                                "text": "<span>2</span>",
                                                "modified": 1612431664366,
                                            },
                                            "path": ["nodes", 1],
                                        }
                                    ],
                                }
                            ],
                        }
                    },
                    "context": {
                        "os": "Windows",
                        "osVersion": "NT 10.0",
                        "appVersion": "2.0.0.825",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal(
                'headers."Content-Type"', "application/json;charset=UTF-8;charset=UTF-8"
            )
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/item_count")
            .post("https://api2.mubu.com/v3/api/list/item_count")
            .with_headers(
                **{
                    "content-length": "41",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTA4OTU1MzYiLCJleHAiOjE2MTUwMjM2NDEsImlhdCI6MTYxMjQzMTY0MX0.KnPbUCPymXPAisYoxKTy7A2YsySJbMm2w6HowJEeUZjFz1EBm5WIzkGk2K1wEM4yZJ5fpDJU4XlcsyPb-sYieg",
                    "Content-Type": "application/json;charset=UTF-8;charset=UTF-8",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36",
                    "data-unique-id": "944e79f5-b0a0-4ac8-8fd3-3d45b810d3b3",
                    "x-request-id": "7314c569-4995-493e-a018-da84ba861c8e",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"folderId": "17-Z9Uagxg", "source": "home"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal(
                'headers."Content-Type"', "application/json;charset=UTF-8;charset=UTF-8"
            )
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "229",
                    "member-id": "8329105351842932",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36",
                    "data-unique-id": "944e79f5-b0a0-4ac8-8fd3-3d45b810d3b3",
                    "Content-Type": "application/json;charset=UTF-8;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTA4OTU1MzYiLCJleHAiOjE2MTUwMjM2NDEsImlhdCI6MTYxMjQzMTY0MX0.KnPbUCPymXPAisYoxKTy7A2YsySJbMm2w6HowJEeUZjFz1EBm5WIzkGk2K1wEM4yZJ5fpDJU4XlcsyPb-sYieg",
                    "request-id": "MESSAGE:10895536:8329105351842932:16",
                    "x-request-id": "6846fde3-69fd-4efa-9460-8248fc54ea19",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "UNWATCH",
                    "reqId": 16,
                    "requestId": "MESSAGE:10895536:8329105351842932:16",
                    "token": "Js82Laivxg",
                    "data": {},
                    "context": {
                        "os": "Windows",
                        "osVersion": "NT 10.0",
                        "appVersion": "2.0.0.825",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal(
                'headers."Content-Type"', "application/json;charset=UTF-8;charset=UTF-8"
            )
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseHogs().test_start()
